/**
 * Webhook Event Value Object
 *
 * Defines the types of events that can trigger webhooks.
 */

export enum WebhookEvent {
  INTERVIEW_STARTED = 'INTERVIEW_STARTED',
  INTERVIEW_COMPLETED = 'INTERVIEW_COMPLETED',
  REPORT_GENERATED = 'REPORT_GENERATED',
  SESSION_PAUSED = 'SESSION_PAUSED',
  SESSION_RESUMED = 'SESSION_RESUMED',
  QUESTION_SKIPPED = 'QUESTION_SKIPPED',
  RESPONSE_SUBMITTED = 'RESPONSE_SUBMITTED',
}
